### ISSUE TITLE
Quality and format not recognized

### ISSUE THREAD

**Issue by vince2corte** [rishabh3354/YOUTUBE-DL-PRO#3]
Hi ! First, great job ! But I found a little bug.
The available quality and video format are not recognized for some Youtube videos. For instance 
https://www.youtube.com/watch?v=xOrzvHtv6_8
So it is not possible to download those videos.
Is it possible to fix that ? Thanx a lot !

**Comment by rishabh3354** [comment]
Thanks for reporting the issue, It has been fixed now.

Please update your app using the cmd below:

`sudo snap refresh youtube-dl-pro `

**Comment by vince2corte** [comment]
Great job ! Works perfectly ! Thanks a lot !
