### ISSUE TITLE
Bug : Download doesn't work

### ISSUE THREAD

**Issue by STYNET** [rishabh3354/YOUTUBE-DL-PRO#4]
Hi,
When i try to download this video (MP4 / 360p-SD) : 
https://youtu.be/Xt_fUItf5Mk
I have a message :  "Unable to download the file !"
My App Version: 2023.7.20
Any idea ?
Thank's

**Comment by royalavenue23** [comment]
Same issue here. Can't download or play.
App version 2023.7.20

**Comment by rishabh3354** [comment]
Hi there, 

Thanks for reporting the issue, it is fixed now. Please update your app to the latest version.

Note: App will be automatically updated to the latest version within 1 day


Thanks and regards
Rishabh

**Comment by royalavenue23** [comment]
Thanks Rishabh! Works like a charm!

**Comment by STYNET** [comment]
Thanks for your fix.. 
it's perfect working now ! :-)
