### ISSUE TITLE
Question: Why is this app uploaded 3 times to Flathub with 3 different names?

### ISSUE THREAD

**Issue by boustanihani** [rishabh3354/YOUTUBE-DL-PRO#6]
Question: Why is this app uploaded 3 times to Flathub with 3 different names:

- https://github.com/rishabh3354/YOUTUBE-DL-PRO
- https://github.com/rishabh3354/TUBE2GO
- https://github.com/rishabh3354/4KTUBE

**Comment by rishabh3354** [comment]
Because All 3 apps have 3 different downloading engines, do you have any problem?
