### ISSUE TITLE
Search results are not working

### ISSUE THREAD

**Issue by chucker8** [rishabh3354/YOUTUBE-DL-PRO#7]
The app is not working. I enter either a search term or enter the URL and no results come back

**Comment by rishabh3354** [comment]
Could you please tell me your platform : windows or linux? Also which country are you from? Sometimes any specific country's servers are under maintenance for temporary basis

**Comment by rishabh3354** [comment]
Also if possible please send issue screenshot which you are facing

**Comment by chucker8** [comment]
hello,i just kept trying and eventually i was able to get results and download.thankyou for getting back to me 
chuck
    On Tuesday, December 3, 2024 at 11:57:05 a.m. EST, Rishabh Bhardwaj ***@***.***> wrote:  
 
 


Also if possible please send issue screenshot which you are facing

**Comment by rishabh3354** [comment]
Thanks for reporting. it is now fixed in new version of the app. i am closing this issue for now.
